version: '3.9'

services:
  node:
    image: ma_super_app:1.0.0
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: upassword
      DATABASE_NAME: lab
    ports:
      - 3000:3000
    links:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: upassword
      MYSQL_DATABASE: lab
      MYSQL_ROOT_PASSWORD: password
