version: '3.9'

services:
  node:
    image: ma_super_app:1.0.0

  mysql:
    image: mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: upassword
      MYSQL_DATABASE: lab
      MYSQL_ROOT_PASSWORD: password
