Version: '3.5'

services:

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: upassword
      MYSQL_DATABASE: lab
      MYSQL_ROOT_PASSWORD: password

  admin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    depends_on:
      - db

