Version: '3.5'

networks:
  - front-end
  - back-end

services:

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: upassword
      MYSQL_DATABASE: lab
      MYSQL_ROOT_PASSWORD: password
    network:
      - back-end

  net:
    image: wbitt/network-multitool
    network:
      - front-end
      - back-end

  admin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    depends_on:
      - db
  network:
    - front-end

