version: '3.9'

services:
  web:
    image: httpd
    volumes:
      - "./app:/usr/local/apache2/htdocs/"
    links:
      - db
    ports:
      - 80:80

  db:
    image: mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: upassword
      MYSQL_DATABASE: lab
      MYSQL_ROOT_PASSWORD: password

  php:
    image: php

  adm:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    depends_on:
      - db